spring:
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache-period: 0
  datasource:
    dirve-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1qaz!QAZ
  jpa:
    hibernate:
      # 若有table存在則不會刪除原本的table
      ddl-auto: update
      # display sql command
      show-sql: true
server:
  port: 8081
  servlet:
    context-path: /api
logging:
  file: logs/application-debug.log