spring:
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache-period: 0
server:
  port: 8081
  servlet:
    context-path: /api
logging:
  file: logs/application-debug.log